language: c
cache: ccache
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - travis-ci/before-install

script:
  - travis-ci/build
